### PR TITLE
Added shorter version by using Math.max

### PR DESCRIPTION
**Pull request by Kaljuk**
A bit shorter version by using the built-in Math module

**Please describe your program and how to run it.**

Gets the largest value from the inserted array

--------
**What Programming Language?**

Javascript

### CODE REVIEW

**Review by wzhouwzhou — DISMISSED** [review]
This program was authored by @vr1e, please either open a PR that does not modify his code (e.g., your own file) or open an issue to request changes from him. You can check CONTRIBUTING.md for more information

**Comment by wzhouwzhou** [comment]
@Kaljuk Just wanted to make sure you are receiving these notifications, your PR has changes requested so please review them

**Review by vr1e — APPROVED** [review]
Approved.

**Comment by wzhouwzhou** [comment]
Thanks vr1e

**Pull request merged**
