### PR TITLE
Add fibonacci in Rust

### PR DESCRIPTION
**Pull request by Unaidedsteak**
**Please describe your program and how to run it.**

A simple one liner to find the nth number in the fibonacci sequence

`rustc fibonnacci.rs && ./fibonnacci`
--------
**What Programming Language?**

Rust

### CODE REVIEW

**Review by wzhouwzhou — CHANGES_REQUESTED** [review]
Would you mind removing the compiled binary? Thanks

**Comment by Unaidedsteak** [comment]
Removed the binary :)

**Review by wzhouwzhou — DISMISSED** [review]
Looks good now, thanks!

**Review by kannagikazuko — CHANGES_REQUESTED** [review]
I do not have commit access to do this myself; please rename the rust file according to the format: username_filename_here.extension

**Comment by kannagikazuko** [comment]
I am also unable to resolve the merge conflict (for the same reason).

**Comment by wzhouwzhou** [comment]
Bump; please give us access or remove conflicts.

**Pull request closed without merging**
