### PR TITLE
Print fibonacci series upto  n terms

### PR DESCRIPTION
**Pull request by Akashdeep98**
**Please describe your program and how to run it.**

This program is written in python language which prints n terms in fibonacci sequence.
This takes n as input and uses a while loop to print fibonacci series with n terms.

--------
**What Programming Language?**

Python

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
In the future, please follow instructions in the Pull Request template by replacing the text instead of removing it altogether; helps with consistency and saves me a tiny bit of time

**Comment by Akashdeep98** [comment]
Sorry for the trouble as I am a beginner to the world of open source and I
will definitely take care of same in future.
Thanks
Regards
Akashdeep
Akashdeep98.github.io

**Comment by wzhouwzhou** [comment]
👍

**Comment by wzhouwzhou** [comment]
I moved this to honorary-one-line-wonders because it is not a one-line program. No worries, you can submit another PR with a new file if you have another program

**Comment by wzhouwzhou** [comment]
Thanks for making your first contribution. If you would like, you can talk a bit about yourself by making a PR that adds your bio to the bottom of the list here: https://github.com/kannagikazuko/one-line-wonders/blob/master/CONTRIBUTORS.md

**Pull request merged**
