### PR TITLE
changed Number

### PR DESCRIPTION
**Pull request by AathmikaM**
**Please describe your program and how to run it.**

...something... (replace this lisdsne)

--------
**What Programming Language?**

...language...

### CODE REVIEW

**Review by wzhouwzhou — CHANGES_REQUESTED** [review]
This program was authored by @edgriebel, please either open a PR that does not modify his code (e.g., your own file) or open an issue to request changes from them. You can check [CONTRIBUTING.md](https://github.com/kannagikazuko/one-line-wonders/blob/master/CONTRIBUTING.md) for more information

**Comment by edgriebel** [comment]
Note that `SortExample.java` is not my code, it was originally committed by @Akash-Sareen . I only moved and renamed it because it was called "java", which would conflict with keeping Java files in a directory called `java`. It looks like github isn't showing the history of the file before my move.

>$ git log --follow SortExample.java
> commit 109ae2e6852f2da0705e09d35e57e921ce7a85e9
> Author: Akash-Sareen <36230675+Akash-Sareen@users.noreply.github.com>
> Date:   Sun Oct 28 18:53:24 2018 +0530
>
>    Java code
>    
>    Code to sort array in one line.

**Comment by wzhouwzhou** [comment]
Oh strange, I just used a quick blame tab to check

**Comment by wzhouwzhou** [comment]
I'm closing this PR due to inactivity; no worries, feel free to open a new one, taking into account the above comments

**Pull request closed without merging**
