### PR TITLE
Adds Solution To Unique Array

### PR DESCRIPTION
**Pull request by subhamX**
**Please describe your program and how to run it.**

```
INPUT FORMAT - 
    SIZE OF ARRAY
    ARRAY ELEMENTS

OUTPUT FORMAT - 
    UNIQUE ARRAY
```

**ANALYSIS**
```
    Insertion in set costs O(log(n)) in average case.
    Thus, For n insertion it will cost O(n * log(n)).

    Insertion in set costs O(n) in worst case.
    Thus, For n insertion it will cost O(n * n).
```
--------
**What Programming Language?**

This solution is using C++

### CODE REVIEW

**Review by kannagikazuko — CHANGES_REQUESTED** [review]
Is there a way you could make this explicitly one line by removing cin or moving user input to the top/elsewhere? Otherwise we can move this to the honorary code folder.

**Comment by subhamX** [comment]
I have removed the code which expects input from the user. Instead, I have assumed an Array Of Elements stored in C Array.

**Review by wzhouwzhou — DISMISSED** [review]
Lines 37-41 are the ones that actually do the inserting, and are compressible to one line, so I'm going to go ahead and approve the PR @kannagikazuko

**Comment by subhamX** [comment]
@wzhouwzhou Should I refine my code further?

**Comment by wzhouwzhou** [comment]
If you wanted to, you can remove the optional { } after the for loop and if statement but it's also great as-is. Feel free to try another challenge to PR!

**Comment by subhamX** [comment]
> Is there a way you could make this explicitly one line by removing cin or moving user input to the top/elsewhere? Otherwise we can move this to the honorary code folder.

@kannagikazuko I have addressed all the issues. Please consider merging my contribution/PR. 🙂

**Review by kannagikazuko — APPROVED** [review]

**Comment by kannagikazuko** [comment]
Looks good now, thanks!

**Pull request merged**
