### PR TITLE
Solved Issue Combinations #381 as powerset.cpp

### PR DESCRIPTION
**Pull request by yashagarwal1999**
The code takes an integer N the size if the array.. The next N lines contains a single integer the array element.

**Please describe your program and how to run it.**

g++ powerset.cpp
./a.out

--------
**What Programming Language?**

c++14

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
I’m not sure this is a one-liner, would you like us to move it to the honorary code folder?

**Comment by yashagarwal1999** [comment]
Yeah. Sorry i didn't know the folder where to put it in

**Review by yashagarwal1999 — COMMENTED** [review]
Added python code for Combination #381

**Comment by wzhouwzhou** [comment]
No worries, we'll take care of it! 👍

**Comment by kannagikazuko** [comment]
The python code has a "one-liner" in the function so I did not need to move it.

**Review by kannagikazuko — APPROVED** [review]

**Pull request merged**
