### PR TITLE
Solved #162

### PR DESCRIPTION
**Pull request by yashagarwal1999**
**Please describe your program and how to run it.**
Solved Largest sum of consecutive numbers in an array in cpp #162
Call the function maxsum which will return a pair of integers when an array and its size is passed is passed
Solved Unique Array #323
Solved #78 in python
 Pi Computation in One Line #78
...something... (replace this line)

--------
**What Programming Language?**
C++,python
...language...

### CODE REVIEW

**Comment by yashagarwal1999** [comment]
Also solved Counting Valley #96

**Comment by yashagarwal1999** [comment]
I have added the files to their respective folders.

**Review by kannagikazuko — CHANGES_REQUESTED** [review]
Please follow the file format `username_filename_here.ext` on all files. Also, if you could put the unique elem/array file in the /unique folder and pi one in approximate_pi, you should see the folders in a file browser.
As for approx pi, you can swap out `def` declaration with a lambda notation.

**Comment by wzhouwzhou** [comment]
Bump

**Comment by yashagarwal1999** [comment]
I am closing this pull request as I have made these changes in #412 please check that thanks

**Comment by yashagarwal1999** [comment]
Please check #412 I have made all the changes and yet it has not been merged. Please let me know if there are any changes in #412 to be done

**Pull request closed without merging**
