### PR TITLE
Create wzhouwzhou_check_brackets.js

### PR DESCRIPTION
**Pull request by wzhouwzhou**
**Please describe your program and how to run it.**

One-liner to make sure your opening/closing brackets line up.

--------
**What Programming Language?**

Javascript

### CODE REVIEW

**Review by diced — APPROVED** [review]
LGTM!

**Comment by rpxs** [comment]
Hello @wzhouwzhou I am sorry to inform you that your Pull Request is more than one line, therefore we cannot accept it.

**Comment by wzhouwzhou** [comment]
Hey @rpxs the last two lines show the usage, the one liner is the first line!

**Comment by rpxs** [comment]
I do not care @wzhouwzhou. I'm letting this slide because you own this repository, but be warned that if I see this happening again, I will take action.

**Comment by wzhouwzhou** [comment]
Thanks for your time, much unappreciated, please touch some grass!

**Comment by rpxs** [comment]
Also, if you didn't see my status, it says that I am busy, and hard at work making billions as a Discord bot developer, please stop pestering me with these GitHub mentions.

**Comment by wzhouwzhou** [comment]
Hey @rpxs, understood, will keep in mind not to @rpxs mention you via @rpxs. It looks like the PR was approved by @diced anyway so I won't need to @rpxs anymore? Please confirm, and good day to you mate!

**Comment by rpxs** [comment]
I am sorry to inform you that I am currently wearing a bracelet weaved with grass at the moment. I do not listen to power-hungry GitHub repository owners who are willing to go to any extent to pull request farm. 

Since this pull request has been marked as too heated, I will concede here, but let this information be known to the rest of the world.

**Comment by wzhouwzhou** [comment]
Hey @diced just want to make sure you're not limiting contributions from the community!

**Comment by rpxs** [comment]
Would you fellow maintainers kindly stop locking and unlocking the pull request, it is not a door. Thanks!

**Comment by wzhouwzhou** [comment]
Absolutely!

**Comment by diced** [comment]
This is a heated pull request, therefore we will not be accepting it.

**Comment by wzhouwzhou** [comment]
Hey @diced just a friendly reminder that the discussion in the PR has nothing to do with the content of the PR.

**Comment by diced** [comment]
Please resubmit the PR so we do not have useless comments in the PR...

**Pull request merged**
