### PR TITLE
Created duplicate remover oneliner

### PR DESCRIPTION
**Pull request by jagw1re**
Solution to issue #323 

**Please describe your program and how to run it.**

The program removes duplicates from a given array and outputs it, in one line (excluding variables).

--------
**What Programming Language?**

C++

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
I think the {} around the for loop blocks are optional which qualifies this as actually a one-liner!

**Comment by jagw1re** [comment]
Yep, you're right! I've updated it to reflect that change :)

**Review by wzhouwzhou — DISMISSED** [review]
If you'd like, feel free to add your bio to CONTRIBUTORS.md!

**Comment by jagw1re** [comment]
Done! Want me to close this request?

**Comment by wzhouwzhou** [comment]
Not yet, we still need to merge it, decide about move it into a dedicated folder for unique_array, etc, but I'll take it from here, thanks!

**Comment by jagw1re** [comment]
No worries!

**Comment by jagw1re** [comment]
I created a JavaScript solution, so I'll create a new PR instead

**Review by wzhouwzhou — DISMISSED** [review]
👍

**Review by wzhouwzhou — APPROVED** [review]

**Pull request merged**
