### PR TITLE
Create wzhouwzhou_add.go

### PR DESCRIPTION
**Pull request by wzhouwzhou**
**Please describe your program and how to run it.**

Adds two ints in langgo. Throw add(5, 6) in your main file or project to use.

--------
**What Programming Language?**

Golang

### CODE REVIEW

**Comment by rpxs** [comment]
What is langgo?

**Comment by wzhouwzhou** [comment]
Golang

**Comment by rpxs** [comment]
Performance wise, is this actually beneficial? I see this as a useless function because one can always just add two numbers the recommended way instead of bloating it with a function.

**Comment by wzhouwzhou** [comment]
Yes! The golang AOT will actually inline this while compiling. It's useful for passing in callbacks via mappers for array structures.

**Review by rpxs — APPROVED** [review]
Nice!

**Pull request merged**
