### PR TITLE
Perl-One-Liner

### PR DESCRIPTION
**Pull request by Ojaswy**
**Please describe your program and how to run it.**

This regular expression is a modified form of a famous Perl One-Liner which matches strings whose length is prime.

--------
**What Programming Language?**

PERL

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
Woah, this is cool. How does it work?

**Review by wzhouwzhou — APPROVED** [review]

**Comment by Ojaswy** [comment]
I guess the reason behind Build failing is that coding such regex in Perl has become obsolete or went out of practice a long time ago.

**Comment by wzhouwzhou** [comment]
Actually, the build failing was an internal file organization check we have on the repository. It tells us that when we merge, we’ll need to move the file into a prime/primes folder.

**Comment by wzhouwzhou** [comment]
If you want to re-open the PR, that’d be cool

**Comment by Ojaswy** [comment]
I am new to PR's and contributing and am still trying to wrap my head around  Builds, Travis CI and stuff. 
There is an Open PR,  so I can't reopen this apparently.

**Comment by wzhouwzhou** [comment]
Ah, I see #344 which has the changes made in this PR plus a new one. We’ll have a look at it, thanks!

**Pull request closed without merging**
