### PR TITLE
Feature/anagram

### PR DESCRIPTION
**Pull request by s-ankur**
#260 Solution C++
**Please describe your program and how to run it.**
<p>
Compile <br>
Input first word <br>
Input Second word <br>
Outputs if these two are anagrams <br>
<p>

--------
**What Programming Language?**

C++

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
(Removed the file so that the PR would have 1 file changed)

**Comment by wzhouwzhou** [comment]
❤️ to std::is_permutation

**Comment by wzhouwzhou** [comment]
250'th Closed Pull Request! 🎉

**Comment by s-ankur** [comment]
@wzhouwzhou the file was removed from the repo entirely somehow.

**Comment by wzhouwzhou** [comment]
@s-ankur if manually copy-pasting the code into a new file or selfmerging a pull request doesn't work, deleting and recreating the fork should fix the issue

**Pull request merged**
