### PR TITLE
Revert "Create wzhouwzhou_check_brackets.js"

### PR DESCRIPTION
**Pull request by rpxs**
this is a good natured joke between friends 😂

### CODE REVIEW

**Comment by diced** [comment]
Please refrain from coming to https://github.com/wzhouwzhou/one-line-wonders.

**Comment by rpxs** [comment]
Excuse me? Are you taking a hard-working maintainer for granted? This situation is just disgusting. Two project maintainers in a position of power insulting one at a lower statute.

**Comment by diced** [comment]
I will have to file a restraining order against you, if this continues.

**Comment by rpxs** [comment]
I am a representative from wzhouwzhou Inc, and I must say that your behavior is outright insane. Please stop commenting on my pull requests before I block you on GitHub.

**Review by wzhouwzhou — CHANGES_REQUESTED** [review]
Please close this PR

**Pull request closed without merging**
