### PR TITLE
Feature/sum of digits

### PR DESCRIPTION
**Pull request by amanagarwal97**
**Please describe your one-line program and how to run it.**
Sum of digits of a string.
`print(f('123456'))`

**What Programming Language?**
Python3

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
Since the files changed is identical to #114 but the documentation for them is split would it be possible to remove the duplicate file from 114/commit the files separately in different PRs from different branches?

**Comment by amanagarwal97** [comment]
I already made different PRs with different branches for this?
Can you explain me the issue exactly

**Comment by wzhouwzhou** [comment]
This current PR (#115) contains code not described in your initial comment:
> Please describe your one-line program and how to run it.
> Sum of digits of a string.
> print(f('123456'))

The diff (https://github.com/kannagikazuko/one-line-wonders/pull/115/files) contains code from #114 which was already merged (python/sieve_of_eratosthenes.py)

To avoid confusion later later when I go back to count some PR and contribution count stats could you remove files from your branch (amanagarwal-sopho:feature/sum_of_digits)/update it with master so that only the file for sum_of_digits.py shows up?

**Comment by amanagarwal97** [comment]
Okay so i deleted the first file in my earlier PR #114 . Is it okay now?

**Comment by wzhouwzhou** [comment]
Yea, thanks

**Pull request merged**
