### PR TITLE
Create T-Primes.cpp

### PR DESCRIPTION
**Pull request by radensaleh**
C++ Primes Algorithm

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
Hi @radensaleh, thanks for your interest! Can you please fill in some of the details in the pull request description? As for the program, there seems to be some code that can be compressed into one line. Please note which "one-line-wonder" applies.

**Review by wzhouwzhou — CHANGES_REQUESTED** [review]
Please let us know which part of this program is the "one-liner" you wish to submit and what it does! Otherwise, feel free to move this to honorary one-liners.

**Comment by wzhouwzhou** [comment]
Bump

**Comment by kannagikazuko** [comment]
T-Primes is one-line, sieve is the setup function.

**Review by kannagikazuko — APPROVED** [review]

**Review by wzhouwzhou — APPROVED** [review]

**Pull request merged**
