### PR TITLE
Two Rust one-liners

### PR DESCRIPTION
**Pull request by Henning-K**
**Please describe your program and how to run it.**

One is a program giving the user the n-th Fibonacci number, the other checks whether the input number is prime or not.

Just use rustc to compile the .rs file(s) and run the resulting binary/ies using any positive integer as an input.

--------
**What Programming Language?**

Rust

### CODE REVIEW

**Review by wzhouwzhou — DISMISSED** [review]

**Review by wzhouwzhou — DISMISSED** [review]
Thank you so much for putting them in their folders! It's not explicitly mentioned anywhere right now but it saves us a lot of time later when we finalise all the PRs!

**Comment by Henning-K** [comment]
> Thank you so much for putting them in their folders! It's not explicitly mentioned anywhere right now but it saves us a lot of time later when we finalise all the PRs!

Yeah, I found out about the folders thing by trawling through the Travis logs and the associated node file and then guessing the mistake from there. It should probably be mentioned somewhere so automatic PR checks don't fail for this (somewhat contrived) reason.

**Comment by wzhouwzhou** [comment]
Agreed, the travis build is currently an incomplete way for maintainers to check whether we have had an open issue related to a program by trying to make an inference from the filename. The develop branch is where we're in the middle of migrating everything over (i.e., usernames in file names, files in folders, bug fixes in the travis build, etc). I currently have almost 100 unstaged files locally that I need to push there, and others may have some more they haven't sent me yet.

The reasoning behind this is typically when we have an open issue suggesting a program, we get significantly more entries related to that issue, which (for the more popular langs) crowd up the language folder. By housing them under a folder, we are able to get a more informative at-a-glance view of program *contents* inside the repository.

Even worse is the fact that once PRs are merged, it often becomes a treasure hunt trying to find the expected output and required input for many of these files, especially given the nature of this project. I had hoped with #236 we'd be able to move towards having comments within the code but many people skip that. That's reasonable for now until we have either a dedicated documentation folder or go in and add comments to all the existing files. (If you're interested in doing so though, do let me know. It's more menial work that's on our to-do list to get done someday, perhaps after the Hacktoberfest rushes.)

If you've made it this far, thanks for staying with me. Apologies on our part, as development has been on the slower side lately. Hopefully once we get the travis and organization stuff turned around, we'll be able to start making our way through correcting and merging the open PRs.

**Comment by Henning-K** [comment]
I added an iterative version of the fibonacci one-liner since the recursive one has such a bad runtime complexity (takes *several* seconds when n>40).

I also added some simple unittests with instructions on how to compile them using rustc.
If I had used Cargo the relevant command would just be `cargo test` but using Cargo for such small programs seemed like overkill to me, especially since there aren't even any dependencies to consider and just the Cargo.toml file would be about as long as the each of the source files.

**Review by wzhouwzhou — DISMISSED** [review]

**Review by kannagikazuko — APPROVED** [review]
Thank you also for following file naming conventions

**Pull request merged**
