### PR TITLE
added a file

### PR DESCRIPTION
**Pull request by sayoojtmc**
**Please describe your program and how to run it.**

A simple timer that "Dings after counting down from 5
to run, use:
node timer.js

--------
**What Programming Language?**
Javascript

### CODE REVIEW

**Review by wzhouwzhou — DISMISSED** [review]
Unfortunately, this is simply just multiple lines of js thrown onto one. If you find a way to actually turn this into a one-liner, feel free to update, otherwise we can move it to the honorary one-line-wonders folder

**Comment by sayoojtmc** [comment]
> Unfortunately, this is simply just multiple lines of js thrown onto one. If you find a way to actually turn this into a one-liner, feel free to update, otherwise we can move it to the honorary one-line-wonders folder

Oh , I thought , since the code is inside setInterval function , it counts as one liner.. sorry.

**Comment by wzhouwzhou** [comment]
The setInterval is a one-line call but the lambda is defined across multiple lines. If you'd like, we can reopen the PR and merge it into the honorary code folder.

**Comment by sayoojtmc** [comment]
> The setInterval is a one-line call but the lambda is defined across multiple lines. If you'd like, we can reopen the PR and merge it into the honorary code folder.

yes, that would be helpful.

**Comment by wzhouwzhou** [comment]
👍

**Comment by sayoojtmc** [comment]
umm... merge?

**Comment by wzhouwzhou** [comment]
Apologies for the delay; https://github.com/wzhouwzhou/one-line-wonders/pull/340#issuecomment-538614272

**Review by kannagikazuko — APPROVED** [review]

**Pull request merged**
