### PR TITLE
Create xander_convert_number_to_one_or_bigger.js

### PR DESCRIPTION
**Pull request by Xander1233**
**Please describe your program and how to run it.**

This line of code will convert a given integer `n`.

If n is 0, it will change it to 1.
If n is smaller than 0, it will use the negative value and change it to positive.

To run it: `convert(<Any given signed integer>);`

--------
**What Programming Language?**

JavaScript

### CODE REVIEW

**Review by rpxs — APPROVED** [review]
LGTM!

**Comment by wzhouwzhou** [comment]
LOL, so much going on here!
By the way, this doesn't work for convert(-1) which still outputs -1 and decimals which obviously get floored via the bitwise operators (i.e., convert(3.6) and convert(-3.6) output 3). Also decimals between 0 and 1 are rounded up to 1. convert(-2) also results in 1.

**Comment by Xander1233** [comment]
ohhh. I will check and fix it ASAP

**Comment by rpxs** [comment]
Add a commit and we'll re-merge.

**Comment by Xander1233** [comment]
👍🏻 but before that, I gonna have to fix it, fish 😂

**Comment by rpxs** [comment]
Pick one or the other 🥇

**Pull request merged**
