### PR TITLE
Added a programme to calculate Factorial of a number.

### PR DESCRIPTION
**Pull request by BalgopalPatro**
**Please describe your program and how to run it.**
I added a programme to calculate factorial of a number .
I used command line argument so for compile my programme run 

g++ balgopal123_factorial.cpp

And for the output run 

 ./a.out n

where n is the number of which factorial should be calculated

--------
**What Programming Language?**

C++

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
Very nice! Also, thank you for actually following the file format and adding your name to Contributors!

**Comment by BalgopalPatro** [comment]
Thank you 
Any other task for me ??

**Comment by BalgopalPatro** [comment]
May I know when you will be merge my PR ???

**Comment by kannagikazuko** [comment]
Thanks for your interest! We’re working on organising and merging many PRs on a rolling basis and resolving some things on our end. In the meantime, please feel free to make another pull request with another branch and new code! Check out the open issues for some ideas!

**Review by wzhouwzhou — DISMISSED** [review]

**Review by kannagikazuko — APPROVED** [review]

**Pull request merged**
