### PR TITLE
Update hello.c

### PR DESCRIPTION
**Pull request by ashu1999**
**Please describe your program and how to run it.**

...something... (replace this line)

--------
**What Programming Language?**

...language...

### CODE REVIEW

**Comment by ashu1999** [comment]
hello world program to be updated in c laguage

**Review by wzhouwzhou — CHANGES_REQUESTED** [review]
Thanks for your interest. Please either open a new PR that does not modify someone else's code. You can check [CONTRIBUTING.md](https://github.com/kannagikazuko/one-line-wonders/blob/master/CONTRIBUTING.md) for more information

In the future, please follow instructions in the template ...
> replace this line

... is so you can replace that line to describe what your program does and the language; helps with consistency and saves me a tiny bit of time

**Comment by wzhouwzhou** [comment]
@ashu1999 hey just following up if you saw my comment above, thanks!

**Comment by wzhouwzhou** [comment]
@ashu1999 I'm closing this PR due to a lack of activity. Feel free to check out open [issues](https://github.com/wzhouwzhou/one-line-wonders/issues) and submit a new PR though!

**Pull request closed without merging**
