### PR TITLE
Height/Maximum depth of a binary tree

### PR DESCRIPTION
**Pull request by mrinal-pandey**
**Please describe your program and how to run it.**

The code snippet could be used to find the maximum depth or height of a binary tree.
To run this code on terminal
javac HeightOfBinaryTree.java //Compiling java program
java HeightOfBinaryTree //Execute

//Sample input
1 //Number of testcases
3 //umber of nodes in the tree
1 2 L 1 3 R //Tree in this format
//Sample Output 
2 //Height of the above binary tree

--------
**What Programming Language?**

Java 11

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
Just want to confirm this is not a one-liner right?

**Comment by wzhouwzhou** [comment]
Filename must be of the format username_file_name_here.extension   java/HeightOfBinaryTree.java

**Comment by mrinal-pandey** [comment]
Hey, How do I rename my file here? Do I close this pull request and create a new one with renamed file?

**Comment by mrinal-pandey** [comment]
Never mind. I created a new one

**Pull request closed without merging**
