### PR TITLE
JS two strings unique letters

### PR DESCRIPTION
**Pull request by jackkav**
**Please describe your program and how to run it.**

run `twoStrings('hello', 'world')`
returns YES
run `twoStrings('hello', 'wrd')`
returns NO

matching python implementation [here](https://github.com/wzhouwzhou/one-line-wonders/blob/master/python/twoStrings.py)
--------
**What Programming Language?**

javascript es6

### CODE REVIEW

**Comment by wzhouwzhou** [comment]
Thanks for linking to the python implementation!

**Comment by wzhouwzhou** [comment]
I'd like to open this up as an issue/enhancement to highlight for everyone to try out. Do you want to create one?

**Comment by jackkav** [comment]
done https://github.com/wzhouwzhou/one-line-wonders/issues/337

**Comment by wzhouwzhou** [comment]
Thanks!

**Review by wzhouwzhou — DISMISSED** [review]

**Comment by kannagikazuko** [comment]
Python file updated to https://github.com/wzhouwzhou/one-line-wonders/blob/master/python/unique/moonblade_twoStrings.py

**Review by kannagikazuko — APPROVED** [review]

**Pull request merged**
